### ISSUE TITLE
`project_id = true` does not work with airbrake 5.4

### ISSUE THREAD

**Issue by delphaber** [errbit/errbit#1102]
`airbrake-ruby` 1.4.1 does a `.to_i` on `project_id` value, so we cannot use `true` anymore.

Can we use a fake number like `99999` ?

**Comment by delphaber** [comment]
```bash
↳ $ rake airbrake:test
/Users/faber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/airbrake-ruby-1.4.1/lib/airbrake-ruby/config.rb:133:in `valid?': undefined method `to_i' for true:TrueClass (NoMethodError)

````

**Comment by nofxx** [comment]
Confirm, also: that's from `airbrake-ruby`, not the same gem. The version works: `1.3.1`, fails: `1.4.1`
Related to #1087

**Comment by weh** [comment]
@stevecrozz issue can be closed (?)

**Comment by stevecrozz** [comment]
Yep. You're right @weh
